# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias lt='ls -ltr'
if [ -f /home/vagrant/.kerl/installs/r16b03/activate ]; then
  . /home/vagrant/.kerl/installs/r16b03/activate
fi